---
title: "HW4"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Packages
```{r load-packages}
library(dplyr)
library(readr)
library(broom)
library(ggplot2)
library(stringr)
library(tidymodels) 
tidymodels_prefer() # Resolves conflicts, prefers tidymodel functions
```

## Data Cleaning
```{r}
executions <- read_csv("executiondata_clean.csv")

executions_clean <- executions %>%
  select(-Name) %>%
  separate(Date, c("Month", "Day", "Year"), sep = "/") %>%
  mutate(VictimMale = case_when(
    str_detect(Victim_Sex, "Male") ~ 1, TRUE ~ 0)) %>% # 1 if there was male victim(s)
  mutate(VictimFemale = case_when(
    str_detect(Victim_Sex, "Female") ~ 1, TRUE ~ 0)) %>% # 1 if there was female victim(s)
  mutate(VictimMixed = case_when(
    (VictimMale==1) & (VictimFemale==1) ~ 1, TRUE ~ 0)) # 1 if the victim(s) were male and female

executions_clean <- executions_clean %>% select(-Victim_Sex, -Day)
executions_clean$Month <-
  as.numeric(as.character(executions_clean$Month))
executions_clean$Year <-
```

 
## Research Question

## Logistic Regression

## Random Forest

## Results

## Conclusion

